# NumPy Operations


* 1) Arithmetic and Logic
    - 1.1) Arithmetic
    - 1.2) Logic
* 2) Universal Array Functions
    - 2.1) max, min, average, sum
    - 2.2) power, sqrt, exp, log
    - 2.3) sin, cos, tan
    - 2.4) dot product

## 1) Arithmetic and Logic

You can easily perform array with array arithmetic, or scalar with array arithmetic. <br>
You can also perform logic operation on array. <br>

**Broadcasting**: a technique in numpy used to make operations on different array sizes like multiply or sum a scaler to an array.

Let's see some examples:

### 1.1) Arithmetic

In [1]:
import numpy as np

arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr / arr

C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
# Also warning, but not an error instead infinity
1 / arr

C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

### 2.2) Logic

In [10]:
arr > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [11]:
arr != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

**We can also do operations on 2-D arrays**

In [12]:
arr = np.random.randint(0,10, (3,3))
arr

array([[7, 1, 3],
       [8, 8, 1],
       [1, 0, 3]])

In [13]:
arr + 3

array([[10,  4,  6],
       [11, 11,  4],
       [ 4,  3,  6]])

In [14]:
arr - 2

array([[ 5, -1,  1],
       [ 6,  6, -1],
       [-1, -2,  1]])

In [15]:
3 * arr

array([[21,  3,  9],
       [24, 24,  3],
       [ 3,  0,  9]])

In [16]:
arr

array([[7, 1, 3],
       [8, 8, 1],
       [1, 0, 3]])

In [17]:
arr + 3 * arr

array([[28,  4, 12],
       [32, 32,  4],
       [ 4,  0, 12]])

In [18]:
arr * arr

array([[49,  1,  9],
       [64, 64,  1],
       [ 1,  0,  9]])

## 2) Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [19]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
matrix = np.random.randint(0, 100, (5, 3))
matrix

array([[97, 44, 13],
       [89, 64, 38],
       [31, 67,  6],
       [55, 76, 72],
       [61, 76, 23]])

### 2.1) max, min, average, sum

**max**

In [21]:
np.max(arr) #same as arr.max()

9

In [22]:
np.max(matrix)

97

In [23]:
np.max(matrix, axis=0)

array([97, 76, 72])

In [24]:
np.max(matrix, axis=1)

array([97, 89, 67, 76, 76])

**min**

In [25]:
np.min(arr) #same as arr.min()

0

In [26]:
np.min(matrix)

6

In [27]:
np.min(matrix, axis=0)

array([31, 44,  6])

In [28]:
np.min(matrix, axis=1)

array([13, 38,  6, 55, 23])

**average**

In [29]:
np.average(arr)

4.5

In [30]:
np.average(matrix)

54.13333333333333

In [31]:
np.average(matrix, axis=0)

array([66.6, 65.4, 30.4])

In [32]:
np.average(matrix, axis=1)

array([51.33333333, 63.66666667, 34.66666667, 67.66666667, 53.33333333])

**sum**

In [33]:
np.sum(arr)

45

In [34]:
np.sum(matrix)

812

In [35]:
np.sum(matrix, axis=0)

array([333, 327, 152])

In [36]:
np.sum(matrix, axis=1)

array([154, 191, 104, 203, 160])

### 2.2) sqrt, exp, log, sin

**power**

In [37]:
np.power(arr, 3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [38]:
np.power(matrix, 3)

array([[912673,  85184,   2197],
       [704969, 262144,  54872],
       [ 29791, 300763,    216],
       [166375, 438976, 373248],
       [226981, 438976,  12167]], dtype=int32)

**sqrt**

In [39]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [40]:
np.sqrt(matrix)

array([[9.8488578 , 6.63324958, 3.60555128],
       [9.43398113, 8.        , 6.164414  ],
       [5.56776436, 8.18535277, 2.44948974],
       [7.41619849, 8.71779789, 8.48528137],
       [7.81024968, 8.71779789, 4.79583152]])

**exp**

In [41]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [42]:
np.exp(matrix)

array([[1.33833472e+42, 1.28516001e+19, 4.42413392e+05],
       [4.48961282e+38, 6.23514908e+27, 3.18559318e+16],
       [2.90488497e+13, 1.25236317e+29, 4.03428793e+02],
       [7.69478527e+23, 1.01480039e+33, 1.85867175e+31],
       [3.10429794e+26, 1.01480039e+33, 9.74480345e+09]])

**log**

In [43]:
np.log(arr)

C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [44]:
np.log(matrix)

array([[4.57471098, 3.78418963, 2.56494936],
       [4.48863637, 4.15888308, 3.63758616],
       [3.4339872 , 4.20469262, 1.79175947],
       [4.00733319, 4.33073334, 4.27666612],
       [4.11087386, 4.33073334, 3.13549422]])

### 2.3) sin, cos, tan

In [45]:
angels_arr = np.linspace(0, 360, 9).reshape(3, 3)
angels_arr

array([[  0.,  45.,  90.],
       [135., 180., 225.],
       [270., 315., 360.]])

In [46]:
angels_arr = (angels_arr * 2 * np.pi) / 360
angels_arr

array([[0.        , 0.78539816, 1.57079633],
       [2.35619449, 3.14159265, 3.92699082],
       [4.71238898, 5.49778714, 6.28318531]])

**sin**

In [47]:
np.sin(angels_arr)

array([[ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00],
       [ 7.07106781e-01,  1.22464680e-16, -7.07106781e-01],
       [-1.00000000e+00, -7.07106781e-01, -2.44929360e-16]])

**cos**

In [48]:
np.cos(angels_arr)

array([[ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17],
       [-7.07106781e-01, -1.00000000e+00, -7.07106781e-01],
       [-1.83697020e-16,  7.07106781e-01,  1.00000000e+00]])

**tan**

In [49]:
np.tan(angels_arr)

array([[ 0.00000000e+00,  1.00000000e+00,  1.63312394e+16],
       [-1.00000000e+00, -1.22464680e-16,  1.00000000e+00],
       [ 5.44374645e+15, -1.00000000e+00, -2.44929360e-16]])

### 2.4) dot product

In [50]:
mat = np.arange(9).reshape(3,3)
vec1 = np.array([1,2,3])

print(mat)
print()
print(vec1)
print()
print(np.dot(vec1, mat))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[1 2 3]

[24 30 36]


In [51]:
vec1.dot(mat)

array([24, 30, 36])

# Great Job!

That's all we need to know for now!