![image.png](attachment:image.png)

# Numpy

Numpy is THE library for scientific computing and linear algebra in Python's community and was designed to give users the best of both worlds in programming languages: the speed of `C` language with the readability and elegance of `Python`.

### Why Numpy?
A question arises that why do we need NumPy when python lists are already there. The answer to it is we cannot perform operations on all the elements of two list directly. For example we cannot multiply two lists directly we will have to do it element wise. This is where the role of NumPy comes into play.

In [1]:
from numpy import *
import numpy as np

Very quick speed comparison to show the staggering difference in performance, don't bother about the code in the following cell.

In [2]:
import numpy as np
import time
import gc # garbage collection
import sys


def compare_times(f1, f2, setup1=None, setup2=None, runs=30):
    print('    format: mean seconds (standard error)', runs, 'runs')
    maxpad = max(len(f.__name__) for f in (f1, f2))
    means = []
    for setup, f in [[setup1, f1], [setup2, f2]]:
        setup = (lambda: tuple()) if setup is None else setup
        
        total_times = []
        for _ in range(runs):
            try:
                gc.disable()
                args = setup()
                
                start = time.time()
                if isinstance(args, tuple):
                    f(*args)
                else:
                    f(args)
                end = time.time()
                
                total_times.append(end - start)
            finally:
                gc.enable()
                
        mean = np.mean(total_times)
        se = np.std(total_times) / np.sqrt(len(total_times))
        print('    {} {:.2e} ({:.2e})'.format(f.__name__.ljust(maxpad), mean, se))
        means.append(mean)
    print('    improvement ratio {:.1f}'.format(means[0] / means[1]))

In [3]:
size = 10 ** 7 
print('create a list 1, 2, ...', size)


def create_list(): return list(range(size))
def create_array(): return np.arange(size, dtype=int)

compare_times(create_list, create_array)

create a list 1, 2, ... 10000000
    format: mean seconds (standard error) 30 runs
    create_list  2.17e-01 (1.61e-03)
    create_array 1.05e-02 (1.19e-04)
    improvement ratio 20.8


In [4]:
import time
num = 10000000
a = np.random.random(num)
b = np.random.random(num)

star = time.time()
c = np.dot(a,b)
en = time.time()
print(c)
print("Verctorize  : " +  str((en -star)*1000) + 'ms')

d =0
start = time.time()
for i in range(num):
    d += a[i]*b[i]
end = time.time()

print(d)
print("Loop version  : " +  str((end -start)*1000) + 'ms')
print("Vectorization is faster by" , (end -start)/(en -star) , 'times')

2499853.3140337653
Verctorize  : 79.79106903076172ms
2499853.3140338575
Loop version  : 3642.7013874053955ms
Vectorization is faster by 45.652996402404774 times


### Convinced about numpy powers? ... Now, let's practice!

#### Q1: Create a 1D array of numbers from 0 to 9.


In [5]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### Q2: Extract all odd numbers from arr.


In [6]:
import numpy as np 
arr1=np.array([1,2,3,4,5,6,7,8,9])
print('Odd numbers:',arr[1::2])


Odd numbers: [1 3 5 7 9]


#### Q3: Replace all odd numbers in arr with -1.


In [7]:
import numpy as np 
arr1=np.array([1,2,3,4,5,6,7,8,9])
Result = np.where(arr1%2 ==1, -1,arr1)
print('Odd numbers:',Result)


Odd numbers: [-1  2 -1  4 -1  6 -1  8 -1]


#### Q4: Convert a 1D array of length 10 to a 2D array with 2 rows


In [8]:
arr3=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=arr3.reshape(2,5)
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#### Q5: compute the square root for each element in the  array
#### ([[1, 2, 3],[2, 3, 4],[4, 5, 6]])


In [9]:
arr4=np.array([[1, 2, 3],[2, 3, 4],[4, 5, 6]])
sq=np.sqrt(arr4)
print(sq)

[[1.         1.41421356 1.73205081]
 [1.41421356 1.73205081 2.        ]
 [2.         2.23606798 2.44948974]]


#### Q6: compute the exponential for each element in the above array


In [10]:
arr4=np.array([[1, 2, 3],[2, 3, 4],[4, 5, 6]])
sq=np.exp(arr4)
print(sq)

[[  2.71828183   7.3890561   20.08553692]
 [  7.3890561   20.08553692  54.59815003]
 [ 54.59815003 148.4131591  403.42879349]]


#### Q7: sample 8 elements from uniform dist ([0, 1)


In [11]:
x = random.uniform(size=(2, 4))
print(x)

[[0.00317065 0.60838314 0.80262049 0.3147239 ]
 [0.29975854 0.1966741  0.68999922 0.20280749]]


#### Q8: Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [12]:
arrx = np.random.randint(0, 11, 5)
print("vector of length 5 filled with arbitrary integers from 0 to 10:",arrx)


vector of length 5 filled with arbitrary integers from 0 to 10: [ 7 10  8  6  8]


#### Q9: Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [13]:
import numpy as np
arr= np.arange(10,22).reshape((3, 4))
print(arr)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


#### Q10: Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [14]:
arr= np.linspace(10, 50, 5)
print(arr)

[10. 20. 30. 40. 50.]


#### Q11: Write a NumPy program to create an array of all the even integers from 30 to 70.

In [15]:
arr=np.arange(30,71,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#### Q12: Write a NumPy program to check whether two arrays are equal (element wise) or not

In [16]:
nums1 = np.array([1,2,3,4,5,6])
nums2 = np.array([1,2,3,4,9,8])
np.set_printoptions(precision=15)
print(nums1 == nums2)
nums1 = np.array([1,2,2,6,5,6])
nums2 = np.array([1,9,8,7,9,8])
np.set_printoptions(precision=15)
print(np.equal(nums1, nums2))

[ True  True  True  True False False]
[ True False False False False False]


* further reading: [visit here](https://www.w3resource.com/python-exercises/numpy/index.php)